site_name: Formation Powershell Niv. 1
repo_name: SynapsysIT/Powershell-Niv.1
repo_url: https://github.com/SynapsysIT/Powershell-Niv.1
theme:
  name: 'material'
  features:
    #- navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    #- toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: 'Roboto'
    code: 'Fira Code'
  logo: assets/logo_rhino.png
  palette:
     - scheme: slate
       primary: red
       toggle:
         icon: material/brightness-4
         name: Switch to light mode
     - scheme: default
       primary: red
       toggle:
         icon: material/brightness-7
         name: Switch to light mode

extra_css:
  - assets/extra.css
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Exécuter des commandes: run_command.md
  - Pipeline & Objets: pipeline_and_objets.md
  - Variables:  
      - variables/index.md
      - Array : variables/array.md
      - Hashtable : variables/hashtable.md
      - PSCustomObject : variables/pscustom.md
  - Test: test.md

